version: '3.4'

services:
  nestcampapi:
    image: nestcampapi
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      PORT: "3000"